project:
  type: website

website:
  title: "isheremet-website"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



